name: Bug Report
description: Created to solve a bug
labels: ["Bug","Triage"]

body:
  - type: markdown
    attributes:
      value: "## Hello world!"
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to help us!
        @Wixonic
  - type: textarea
    attributes:
      label: Description
      placeholder: A concise description of your problem..
    validations:
      required: true
  - type: dropdown
    attributes:
      label: OS
      description: |
        Choose the **OS you use**.
        If it doesn't appear, it may not be supported.
      options:
        - iOS / iPadOS
        - Android
        - MacOS
        - Windows
        - Linux
        - Other
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Browser
      description: |
        Choose the **browser you use**.
        If it doesn't appear, it may not be supported.
      options:
        - Safari
        - Chrome
        - Firefox
        - Other
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct and Contributing Guidelines
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Wixonic/WebCraft/blob/Default/CODE_OF_CONDUCT.md) and our [Contributing Guidelines](https://github.com/Wixonic/WebCraft/blob/Default/CONTRIBUTING.md).
      options:
        - label: I agree to follow this project's Code of Conduct and Contributing Guidelines
          required: true
